### ISSUE TITLE
Add readme.md for each component in the repo

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-app-components#16]
As per @olegrise 's suggestion here: https://github.com/Rise-Vision/common-app-components/pull/15.

Add readme w/ component information, usage & example for easier re-use.

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc is this issue still open and if it is do you concur that the above needs to be done? Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison @alex-deaconu I don't think it is worth doing it, as there is a lot to be done without much in return. Docs get deprecated pretty fast. When I need to use a component I look at repos where they are being used or test files. Thoughts? Thanks!

**Comment by ByronDarlison** [comment]
@ezequielc agreed. Closing
